import React from "react";
import { CgWorkAlt } from "react-icons/cg";
import { MdPersonSearch } from "react-icons/md";
import { LuGraduationCap } from "react-icons/lu";
import tokstokProjectImg from "@/../public/tokstok-project.png";
import yamahaProjectImg from "@/../public/yamaha-project.png";
import carrefourProjectImg from "@/../public/carrefour-project.png";
import salonlineProjectImg from "@/../public/salonline-project.png";
import livelobradesProjectImg from "@/../public/livelobradescoseguros-project.png";
import {
  BsHouse,
  BsBookHalf,
  BsPencilSquare,
  BsCodeSquare,
  BsFillEnvelopePaperFill,
  BsPersonBadgeFill,
} from "react-icons/bs";

export const links = [
  {
    name: "Home",
    hash: "#home",
    icon: React.createElement(BsHouse),
  },
  {
    name: "Sobre",
    hash: "#about",
    icon: React.createElement(MdPersonSearch),
  },
  {
    name: "Experiência",
    hash: "#experience",
    icon: React.createElement(BsPersonBadgeFill),
  },
  {
    name: "Projetos",
    hash: "#projects",
    icon: React.createElement(BsPencilSquare),
  },
  {
    name: "Habilidades",
    hash: "#skills",
    icon: React.createElement(BsCodeSquare),
  },
  {
    name: "Cursos",
    hash: "#courses",
    icon: React.createElement(BsBookHalf),
  },
  {
    name: "Contato",
    hash: "#contact",
    icon: React.createElement(BsFillEnvelopePaperFill),
  },
] as const;

export const experiencesData = [
  {
    title: "Full Stack Developer | CAOA Chery",
    location: "São Paulo, SP",
    description:
      "Atuação de ponta a ponta no levantamento, análise e documentação de requisitos para novas aplicações web. Desenvolvimento, evolução e sustentação de soluções que apoiam o atendimento ao cliente e a gestão do negócio, com foco em qualidade, estabilidade e melhoria contínua. Condução de análises de falhas, correção de bugs, otimização de sistemas e alinhamentos técnicos com stakeholders e parceiros.",
    icon: React.createElement(CgWorkAlt),
    date: "Abr/2026 - Atualmente",
    flags: [
      "React Native",
      "Next.js",
      "Node.js",
      "Azure DevOps",
      "Insomnia",
      "SQL Server",
      "Android Apps",
      "iOS Apps",
    ],
  },
  {
    title: "Pós-graduação em Desenvolvimento Web",
    location: "SENAC SP",
    description: "Conclusão: agosto de 2026",
    icon: React.createElement(LuGraduationCap),
    date: "2025 - 2026",
    flags: [],
  },
  {
    title: "Analista de Sistemas | SESC SP",
    location: "São Paulo, SP",
    description:
      "Responsável pelo levantamento, análise e documentação de requisitos funcionais e não funcionais, além do desenvolvimento, evolução e sustentação de aplicações web. Atuação na resolução de incidentes, correção de bugs, otimização de sistemas e condução de reuniões técnicas com stakeholders e parceiros.",
    icon: React.createElement(CgWorkAlt),
    date: "Jul/2024 - Dez/2025",
    flags: [
      "React.js",
      "Next.js",
      "Angular",
      "JavaScript",
      "Java 7/8",
      "Spring Framework",
      "MySQL",
      "Oracle Database",
      "Git",
      "GitHub",
      "Bitbucket",
      "Azure DevOps",
      "Insomnia",
      "Postman",
    ],
  },
  {
    title: "Analista de Sistemas Sênior | Salon Line",
    location: "Barueri, SP",
    description:
      "Atuação no desenho de arquiteturas front-end e no desenvolvimento de funcionalidades, hotsites, landing pages e aplicações web para Oracle Commerce Cloud e WordPress. Liderança técnica em integrações entre e-commerce, ERP, CRM e TMS, com uso de Oracle Integration Cloud e Digibee, além de testes, documentação e suporte ao go-live.",
    icon: React.createElement(CgWorkAlt),
    date: "Jan/2023 - Nov/2023",
    flags: [
      "React.js",
      "Knockout.js",
      "JavaScript",
      "HTML",
      "CSS",
      "WordPress",
      "Oracle Commerce Cloud",
      "Oracle Integration Cloud",
      "Oracle Database",
      "MySQL",
      "Git",
      "Jira",
      "Trello",
      "Notion",
      "Figma",
      "Visio",
      "Linx Commerce",
      "Digibee",
      "TOTVS Protheus",
    ],
  },
  {
    title: "Analista de Sistemas E-commerce Sênior | Carrefour",
    location: "São Paulo, SP",
    description:
      "Desenvolvimento e sustentação do e-commerce VTEX IO e do portal BackOffice, com definição e padronização de arquiteturas front-end. Atuação em code reviews, cerimônias ágeis e resolução de incidentes por análise de causa raiz, contribuindo para a qualidade e a continuidade da operação.",
    icon: React.createElement(CgWorkAlt),
    date: "Ago/2021 - Jan/2023",
    flags: [
      "React.js",
      "TypeScript",
      "JavaScript",
      "HTML",
      "CSS",
      "PostgreSQL",
      "Git",
      "GitHub",
      "GitLab",
      "Jira",
      "GCP",
      "VTEX IO",
    ],
  },
  {
    title: "Desenvolvedor Front-end Sênior | Compass.UOL",
    location: "São Paulo, SP",
    description:
      "Levantamento de requisitos e desenvolvimento de funcionalidades para Oracle Commerce Cloud e WordPress. Definição de padrões de código, realização de code reviews, produção de documentação técnica e participação ativa em cerimônias ágeis orientadas por Scrum.",
    icon: React.createElement(CgWorkAlt),
    date: "Dez/2019 - Ago/2021",
    flags: [
      "JavaScript",
      "HTML",
      "CSS",
      "Knockout.js",
      "Oracle Database",
      "Git",
      "GitLab",
      "Jira",
      "Postman",
      "Oracle Commerce Cloud",
    ],
  },
  {
    title: "Desenvolvedor Front-end Pleno | Tok&Stok E-commerce",
    location: "Barueri, SP",
    description:
      "Desenvolvimento e sustentação de funcionalidades para e-commerce e site institucional, com análise e resolução de bugs, code reviews e participação no levantamento de requisitos. Criação de componentes e evolução de soluções para IBM WebSphere Commerce e VTEX.",
    icon: React.createElement(CgWorkAlt),
    date: "Jan/2012 - Nov/2019",
    flags: [
      "HTML",
      "CSS",
      "JavaScript",
      "jQuery",
      "Dojo.js",
      "Backbone.js",
      "Oracle Database",
      "IBM WebSphere Commerce",
      "VTEX Legacy",
    ],
  },
  {
    title: "Assistente de Marketing Sr. | Tok&Stok",
    location: "Barueri, SP",
    description:
      "Experiência que consolidou a visão de negócio e de experiência digital: produção e tratamento de imagens, organização do acervo, cadastro de produtos no site, criação de comunicados digitais e manutenção da intranet corporativa.",
    icon: React.createElement(CgWorkAlt),
    date: "Dez/2006 - Dez/2011",
    flags: [
      "Oracle Database",
      "HTML",
      "CSS",
      "JavaScript",
      "Dojo.js",
      "Backbone.js",
      "Raphael.js",
      "jQuery",
      "Adobe Photoshop",
    ],
  },
  {
    title: "Bacharelado em Sistemas de Informação",
    location: "UNIBAN – Campus Osasco",
    description: "Conclusão: 2011",
    icon: React.createElement(LuGraduationCap),
    date: "2011",
    flags: [],
  },
] as const;

export const projectsData = [
  {
    title: "CAOA Dashboards",
    description:
      "Dashboards operacionais para acompanhamento de informações e apoio à tomada de decisão no negócio automotivo.",
    tags: ["React", "Next.js", "Node.js", "SQL Server", "Azure DevOps"],
    imageUrl: "/em-breve-projeto.svg",
    linkUrl: "https://salonline.com.br/",
  },
  {
    title: "CAOA Sites Operacionais",
    description:
      "Sites e aplicações operacionais para apoiar processos internos, atendimento ao cliente e evolução da operação.",
    tags: ["React", "Next.js", "Node.js", "Azure DevOps"],
    imageUrl: "/em-breve-projeto.svg",
    linkUrl: "https://salonline.com.br/",
  },
  {
    title: "CAOA Agentes de IA",
    description:
      "Iniciativas com agentes de inteligência artificial para ampliar a eficiência operacional e apoiar novos fluxos de atendimento.",
    tags: ["Agentes de IA", "Node.js", "React", "Integrações", "Azure DevOps"],
    imageUrl: "/em-breve-projeto.svg",
    linkUrl: "https://salonline.com.br/",
  },
  {
    title: "SESC SP APP",
    description:
      "Aplicação mobile voltada à experiência digital do SESCSP, com foco em acesso a serviços, conteúdo e jornadas para o público.",
    tags: ["React Native", "Android", "iOS", "Node.js", "Azure DevOps"],
    imageUrl: "/em-breve-projeto.svg",
    linkUrl: "https://salonline.com.br/",
  },
  {
    title: "Site Bilheteria",
    description:
      "Plataforma web para consulta e compra de ingressos, com foco em usabilidade, clareza da jornada e integração com os serviços do SESC SP.",
    tags: ["React.js", "Next.js", "JavaScript", "Java", "Azure DevOps"],
    imageUrl: "/em-breve-projeto.svg",
    linkUrl: "https://salonline.com.br/",
  },
  {
    title: "Salon Line",
    description:
      "Desenvolvimento e sustentação do e-commerce, combinando novas funcionalidades, hotsites, landing pages e integrações entre plataformas. Participação na preparação técnica e no suporte ao go-live.",
    tags: [
      "Oracle Commerce Cloud",
      "React.js",
      "WordPress",
      "Oracle Integration Cloud",
      "Digibee",
      "Linx Commerce",
    ],
    imageUrl: salonlineProjectImg,
    linkUrl: "https://salonline.com.br/",
  },
  {
    title: "Carrefour",
    description:
      "Evolução do e-commerce VTEX IO e do portal BackOffice, com foco em arquitetura front-end, manutenção sustentável, code reviews e investigação de incidentes.",
    tags: [
      "VTEX IO",
      "React.js",
      "TypeScript",
      "GCP",
      "Microfrontends",
      "BackOffice",
    ],
    imageUrl: carrefourProjectImg,
    linkUrl: "https://www.carrefour.com.br/",
  },
  {
    title: "Yamaha Motor",
    description:
      "Evolução da jornada digital do e-commerce com carrossel 360°, simulação de financiamento em tempo real e landing pages com experiências interativas.",
    tags: ["Oracle Commerce Cloud", "Knockout.js", "jQuery", "Bootstrap", "Responsive"],
    imageUrl: yamahaProjectImg,
    linkUrl: "https://www.yamaha-motor.com.br/",
  },
  {
    title: "Livelo",
    description:
      "Desenvolvimento de funcionalidades e integrações de alta complexidade, com foco em estabilidade, manutenção e evolução da jornada do usuário.",
    tags: ["Oracle Commerce Cloud", "Knockout.js", "jQuery", "Responsive"],
    imageUrl: livelobradesProjectImg,
    linkUrl: "https://www.livelo.com.br/",
  },
  {
    title: "Tok&Stok E-commerce",
    description:
      "Atuação em múltiplas versões do e-commerce, unindo desenvolvimento front-end, sustentação de componentes legados e evolução contínua da plataforma.",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "jQuery",
      "Dojo.js",
      "IBM WebSphere Commerce",
      "VTEX Legacy",
    ],
    imageUrl: tokstokProjectImg,
    linkUrl: "https://www.tokstok.com.br/",
  },
] as const;

export const skillsData = [
  "HTML5",
  "CSS3",
  "JavaScript (ES6+)",
  "TypeScript",
  "React.js",
  "Next.js",
  "React Native",
  "Angular",
  "Knockout.js",
  "jQuery",
  "Dojo.js",
  "Backbone.js",
  "Bootstrap",
  "Node.js",
  "Java 7/8",
  "Spring Framework",
  "MySQL",
  "PostgreSQL",
  "Oracle Database",
  "SQL Server",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Azure DevOps",
  "Postman",
  "Insomnia",
  "Jira",
  "Trello",
  "Notion",
  "Figma",
  "Visio",
  "GCP",
  "Oracle Cloud",
  "Oracle Commerce Cloud",
  "VTEX IO",
  "IBM WebSphere Commerce",
  "Oracle Integration Cloud",
  "Linx Commerce",
  "WordPress",
  "GitHub Copilot",
  "Google Gemini",
  "AWS CodeWhisperer",
  "Blackbox AI",
  "Tabnine",
  "Claude Code",
  "Codex",
] as const;

export const cousersData = [
  {
    title: "Produtividade com IA",
    institution: "Rocketseat",
    workload: "5h",
    initialDate: "26/03/2024",
    endDate: "01/04/2024",
  },
  {
    title: "Clean Code",
    institution: "Rocketseat",
    workload: "5h",
    initialDate: "22/03/2024",
    endDate: "26/03/2024",
  },
  {
    title: "Redux + Zustand",
    institution: "Rocketseat",
    workload: "3h",
    initialDate: "11/03/2024",
    endDate: "18/03/2024",
  },
  {
    title: "Next.js App Router e Testes",
    institution: "Rocketseat",
    workload: "6h",
    initialDate: "28/01/2024",
    endDate: "15/03/2024",
  },
  {
    title: "Formação Node.js",
    institution: "Rocketseat",
    workload: "50h",
    initialDate: "28/11/2023",
    endDate: "26/01/2024",
  },
  {
    title: "React.js",
    institution: "Alura",
    workload: "12h",
    initialDate: "01/03/2022",
    endDate: "01/03/2022",
  },
  {
    title: "React.js, Redux e React Native",
    institution: "Impacta Treinamentos",
    workload: "40h",
    initialDate: "28/09/2019",
    endDate: "09/11/2019",
  },
  {
    title: "jQuery",
    institution: "Impacta Treinamentos",
    workload: "40h",
    initialDate: "01/11/2015",
    endDate: "30/11/2015",
  },
  {
    title: "JavaScript",
    institution: "Impacta Treinamentos",
    workload: "40h",
    initialDate: "12/04/2014",
    endDate: "24/05/2014",
  },
] as const;
